services:
  # PostgreSQL база данных
  postgres:
    image: postgres:17.5-alpine
    environment:
      PGDATA: /var/lib/postgresql/data
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - real_estate_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis для Celery
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - real_estate_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # FastAPI приложение
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - real_estate_network
    volumes:
      - "./app:/backend/app"

  # Celery worker
  celery_worker:
    build: .
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - real_estate_network
    command: celery -A app.worker.celery_app worker --loglevel=info

  # Celery beat (планировщик задач)
  celery_beat:
    build: .
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - real_estate_network
    command: celery -A app.worker.celery_app beat --loglevel=info

volumes:
  postgres_data:

networks:
  real_estate_network:
    driver: bridge


