import type React from "react"
import {
  Users,
  Home,
  DollarSign,
  Building,
  Heart,
  FileText,
  ShieldCheck,
  UserCheck,
  Gavel,
  BarChart2,
  Eye,
  TrendingUp,
  Star,
} from "lucide-react"
import type { Project, Lead, StatCard, FilterOptions, UserRole } from "./types"

/* ---------------------------  ГЛАВНАЯ СТАТИСТИКА  --------------------------- */
export const homeStats = [
  { label: "Проектов в базе", value: "150+", icon: Home },
  { label: "Застройщиков", value: "30+", icon: Users },
  { label: "Сделок в месяц", value: "500+", icon: TrendingUp },
  { label: "Экономия на комиссии", value: "до 5%", icon: Star },
] satisfies { label: string; value: string; icon: React.ComponentType<any> }[]

export const filterOptions = {
  regions: ["Краснодар", "Сочи", "Новороссийск", "Анапа"],
  classes: ["Эконом", "Комфорт", "Бизнес", "Элит"],
  completion: ["Сдан", "2024", "2025", "2026"],
  status: ["В продаже", "Строится", "Сдан", "План"]
}

export const projectsData: Project[] = [
  {
    id: "1",
    name: "ЖК Солнечный Берег",
    developer: "ЮгСтройИмпериал",
    location: "Краснодар, р-н Гидростроителей",
    price: "от 4.8М ₽",
    class: "Комфорт",
    completion: "2025",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rating: 4.9,
    reviews: 124,
    features: ["Паркинг", "Детская площадка", "Рядом с парком"],
    status: "Активный",
    totalApartments: 500,
    sold: 250,
    available: 250,
    revenue: "1.25 млрд ₽",
    leads: 120,
    isFavorite: true,
    promotion: "Ипотека 0.1%",
  },
  {
    id: "2",
    name: "ЖК Зеленый Квартал",
    developer: "Setl Group",
    location: "Санкт-Петербург, Московский р-н",
    price: "от 6.2М ₽",
    class: "Бизнес",
    completion: "Сдан",
    images: ["/placeholder.svg?height=400&width=600"],
    rating: 4.7,
    reviews: 88,
    features: ["Паркинг", "Закрытая территория"],
    status: "Активный",
    totalApartments: 300,
    sold: 280,
    available: 20,
    revenue: "1.7 млрд ₽",
    leads: 45,
    isFavorite: false,
    promotion: "Скидка 10%",
  },
  {
    id: "3",
    name: "ЖК Морская Симфония",
    developer: "Альпика Групп",
    location: "Сочи, Адлерский р-н",
    price: "от 12.5М ₽",
    class: "Элит",
    completion: "2024",
    images: ["/placeholder.svg?height=400&width=600"],
    rating: 4.9,
    reviews: 210,
    features: ["Паркинг", "Закрытая территория", "Рядом с парком"],
    status: "Завершен",
    totalApartments: 150,
    sold: 145,
    available: 5,
    revenue: "1.8 млрд ₽",
    leads: 30,
    isFavorite: true,
  },
  {
    id: "4",
    name: "ЖК Центральный",
    developer: "ССК",
    location: "Краснодар, Центральный р-н",
    price: "от 5.1М ₽",
    class: "Комфорт",
    completion: "2024",
    images: ["/placeholder.svg?height=400&width=600"],
    rating: 4.6,
    reviews: 150,
    features: ["Паркинг", "Детская площадка"],
    status: "Активный",
    totalApartments: 800,
    sold: 400,
    available: 400,
    revenue: "2 млрд ₽",
    leads: 250,
    isFavorite: false,
    promotion: "Паркинг в подарок",
  },
]

export const leadsData: Lead[] = [
  {
    id: "1",
    name: "Иван Петров",
    phone: "+7 (918) 123-45-67",
    email: "ivan.p@example.com",
    project: "ЖК Солнечный Берег",
    apartment: "2-комнатная, 65м²",
    status: "Новая",
    date: "2024-07-21",
  },
  {
    id: "2",
    name: "Елена Сидорова",
    phone: "+7 (928) 765-43-21",
    email: "elena.s@example.com",
    project: "ЖК Центральный",
    apartment: "Студия, 28м²",
    status: "В работе",
    date: "2024-07-20",
  },
  {
    id: "3",
    name: "Сергей Иванов",
    phone: "+7 (999) 555-12-34",
    email: "sergey.i@example.com",
    project: "ЖК Зеленый Квартал",
    apartment: "3-комнатная, 88м²",
    status: "Закрыта",
    date: "2024-07-19",
  },
]

export const reviewsData = [
  {
    id: "1",
    author: "Алексей Смирнов",
    role: "Покупатель",
    text: "Отличная платформа! Нашли квартиру мечты без риелторов и скрытых комиссий. Все прозрачно и понятно. Рекомендую!",
    avatar: "/placeholder.svg?height=48&width=48",
  },
  {
    id: "2",
    name: "Ольга Кузнецова",
    role: "Покупатель",
    text: "ИИ-подбор — это просто магия! Сэкономила кучу времени, система предложила варианты, о которых я даже не думала. Спасибо!",
    avatar: "/placeholder.svg?height=48&width=48",
  },
  {
    id: "3",
    name: "Виктор Петров",
    role: "Представитель застройщика",
    text: "Перевели все наши проекты на эту платформу. Результат — рост прямых продаж на 30% и значительная экономия на рекламе.",
    avatar: "/placeholder.svg?height=48&width=48",
  },
]

export const dashboardStats: Record<UserRole, StatCard[]> = {
  developer: [
    { label: "Активных проектов", value: "5", icon: Building, change: "+1" },
    { label: "Новых заявок", value: "28", icon: Users, change: "+15%" },
    { label: "Продаж за месяц", value: "12", icon: Home, change: "+8%" },
    { label: "Выручка", value: "72.4М ₽", icon: DollarSign, change: "+12%" },
  ],
  buyer: [
    { label: "В избранном", value: "8", icon: Heart },
    { label: "Мои заявки", value: "3", icon: FileText },
    { label: "Просмотрено", value: "25", icon: Eye },
    { label: "Рекомендаций", value: "12", icon: UserCheck },
  ],
  admin: [
    { label: "Всего застройщиков", value: "32", icon: Building },
    { label: "На модерации", value: "3", icon: ShieldCheck },
    { label: "Жалобы", value: "1", icon: Gavel },
    { label: "Общий оборот", value: "1.8Б ₽", icon: BarChart2 },
  ],
}
