version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    network_mode: "host"
    environment:
      - NEXT_PUBLIC_API_HOST=${NEXT_PUBLIC_API_HOST:-localhost}
      - NEXT_PUBLIC_API_PORT=${NEXT_PUBLIC_API_PORT:-3000}
      - HOST=${HOST:-localhost}
      - PORT=${PORT:-3000}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev 